name: Go-Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Go mod tidy
        run: go mod tidy

      - name: Go fmt
        run: go fmt ./...

      - name: Go vet
        run: go vet ./...
